### ISSUE TITLE
Windows Use of PIMS

### ISSUE THREAD

**Issue by apiszcz** [soft-matter/pims#197] opened 2015-11-07 19:14 UTC
Attempting to use PIMS with stacked TIFF, open to other approaches and any format that I can create from Windows. (MY ERROR) corrected

WRITE:
    tifoutpath=r'C:\tmp\data.tif'
    tifout=tiffile.TiffWriter(tifoutpath,bigtiff=True)
    ...
    tifout.save(imdata)
tifout.close()

READ
frames = pims.TiffStack(r'C:\tmp\data.tif', as_grey=True)
All set, using python tifffile.py for now.

**Comment by danielballan** [comment] 2015-11-07 19:17
Did you install tifffile using conda?

**Comment by apiszcz** [comment] 2015-11-07 19:25
​Negative, I need to set this up without CONDA, so I'm looking for any
format I can use PIMS with that might support that. Almost seems like a
stack numpy array would be the easiest.

**Comment by apiszcz** [comment] 2015-11-07 20:00
Possible bug?
PIMS does not appear to see sequence when written with compress option?
tifout.save(fgmask) # works, sees all 500 frames

tifout.save(fgmask,compress=9) # only sees 1 frame on read

**Comment by apiszcz** [comment] 2015-11-07 20:06
Attempted ANCONDA 3 (python 3.5 install) it seems as if libtiff and av not supported yet.

**Comment by apiszcz** [comment] 2015-11-07 20:11
I see possible support for tiff in scikit image also, however TiffStack appears to omit that library. http://scikit-image.org/docs/stable/api/skimage.external.tifffile.html

**Comment by danielballan** [comment] 2015-11-07 21:39
I would suggest HDF5 and h5py over numpy binaries. Video formats are big headache -- I would not suggest using mp4 if you can avoid it.

**Comment by caspervdw** [comment] 2015-11-07 22:55
If I understand correctly,  the issue is that `pims.TiffStack` does not work correctly on compressed tiffs. Wich backend reader are you using? Tiffstack_tifffile?  You could give Tiffstack_pil or Tiffstack_libtiff a try.

**Comment by apiszcz** [comment] 2015-11-08 07:26
That was my next plan thank you

**Comment by apiszcz** [comment] 2015-11-08 07:27
I tried both they also do not support compression I will look into HDF

**Comment by apiszcz** [comment] 2015-11-08 19:38
I tried all three. I implemented an inerrable reader that loads HDF
frames.​ It is working for now. Stacked or sequence TIFF seemed 'simpler'
at first.

On Sat, Nov 7, 2015 at 5:55 PM, Casper van der Wel <notifications@github.com

**Comment by tacaswell** [comment] 2015-11-12 15:58
@apiszcz Can you push your hdf reader upstream?

**Comment by apiszcz** [comment] 2015-11-12 17:40
It is probably not ready for prime and I just noted GROUP /fram
exceeding the recommended maximum number of children 16,384


# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
class TrackHDFIterable:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    def __init__(self,h5path=''):
        self.p=h5path
        self.hdf=pd.HDFStore(self.p)
        self.frames=int((len(self.hdf.keys())-3)/2)  # this will vary
for storage setup
        self.lo=2
        self.high=self.frames
        self.current=self.lo

    def __iter__(self):
        return self

    def __next__(self):
        if self.current>self.high:
            raise StopIteration
        else:
            framename='frame/f%09d/data'%int(self.current)
            self.current+=1
            return self.hdf[framename].as_matrix()

**Comment by apiszcz** [comment] 2015-11-12 21:22
OpenCV version

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
class TrackBatchIterableOpenCV:
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    def __init__(self,videopath=''):
        self.videopath=videopath
        self.cap=cv2.VideoCapture(videopath)
        self.fps=self.cap.get(cv2.CAP_PROP_FPS)
        self.frames=int(self.cap.get(cv2.CAP_PROP_FRAME_COUNT))
        self.lo=0
        self.high=self.frames
        self.current=self.lo

    def __iter__(self):
        return self

    def __next__(self):
        if self.current>=self.high:
            raise StopIteration
        else:
            xx=self.cap.read()[1]
            self.current=int(self.cap.get(cv2.CAP_PROP_POS_FRAMES))
            xx=cv2.cvtColor(xx,cv2.COLOR_BGR2GRAY)
            return xx

**Comment by caspervdw** [comment] 2015-12-08 20:32
Thanks @apiszcz for sharing your code. I am opening an issue to wrap opencv so that this code doesn't get lost in the history. Closing this.

**Closed by caspervdw** 2015-12-08 20:32 UTC
