### ISSUE TITLE
Error : list indices must be integers or slices, not av.video.stream.VideoStream

### ISSUE THREAD

**Issue by Ysenberg** [soft-matter/pims#306] opened 2018-07-16 15:08 UTC
Hi all, 

I'd like to open a .mov video obtained using a Nikon camera. So I tried to 

```
import pims
v = pims.Video('Lam0_V16.mov')
```

but I get the following error message that I don't understand. Do you know what's happening there ?

```
`TypeError                                 Traceback (most recent call last)
<ipython-input-3-1b306d78deb4> in <module>()
----> 1 v = pims.Video('Lam0_V16.mov')

/usr/local/lib/python3.5/dist-packages/pims/pyav_reader.py in __init__(self, filename, cache_size, fast_forward_thresh, stream_index)
    137         # obtain first frame to get first time point
    138         # also tests for the presence of timestamps
--> 139         frame = next(_gen_frames(demuxer, self._stream.time_base))
    140         self._first_pts = frame.metadata['timestamp']
    141 

/usr/local/lib/python3.5/dist-packages/pims/pyav_reader.py in _gen_frames(demuxer, time_base, frame_rate, first_pts)
     52 
     53 def _gen_frames(demuxer, time_base, frame_rate=1., first_pts=0):
---> 54     for packet in demuxer:
     55         for frame in packet.decode():
     56             # learn timestamp

av/container/input.pyx in demux()

av/container/streams.pyx in ### _flatten()

TypeError: list indices must be integers or slices, not av.video.stream.VideoStream`
```
Thanks a lot for your help, 
Ysen.

**Comment by nkeim** [comment] 2018-07-16 15:45
Hi! Thanks for reporting this. See #296 for a workaround. The problem is fixed in the development version.

**Closed by nkeim** 2018-07-16 15:45 UTC
