### ISSUE TITLE
PyAVReaderTimed compatibility with PyAV 6.2

### ISSUE THREAD

**Issue by ChaseD13** [soft-matter/pims#332] opened 2019-10-16 20:13 UTC
Hello,
Similar to issue #296, I am attempting to use pims to import an .avi video, and as such I need pims.Video(). However, when I attempt to use it, I get an error message that "list indices must be integers or slices, not av.video.stream.VideoStream".

Here is the code I am running:
cap = pims.Video("D:\Donaldson Lab\Current Work\Video Split Gui\voleChopper.py")

Here is the Traceback:
 File "D:\Donaldson Lab\Current Work\Video Split Gui\voleChopper.py", line 456, in <module>
    importVideo()
  File "D:\Donaldson Lab\Current Work\Video Split Gui\voleChopper.py", line 305, in importVideo
    cap = pims.Video(VIDEO_PATH) #use numpy slicing to access frames, areas within frame: vid[0] = frame 0
  File "C:\Users\Behavior Scoring\Anaconda3\lib\site-packages\pims\pyav_reader.py", line 139, in __init__
    frame = next(_gen_frames(demuxer, self._stream.time_base))
  File "C:\Users\Behavior Scoring\Anaconda3\lib\site-packages\pims\pyav_reader.py", line 54, in _gen_frames
    for packet in demuxer:
  File "av\container\input.pyx", line 111, in demux
  File "av\container\streams.pyx", line 50, in _flatten
TypeError: list indices must be integers or slices, not av.video.stream.VideoStream

I will try to switch PyAv to 0.4, but I feel like this should be updated for 6.2. Thank you in advance.

**Comment by ChaseD13** [comment] 2019-10-16 20:21
QUICK FIX:
    Uninstall av from conda environment

**Comment by ythomashu** [comment] 2019-11-26 16:04
I'm having a the same error when opening video files (even after uninstalling av from conda environment.)
TypeError: list indices must be integers or slices, not av.video.stream.VideoStream
Any suggestion?

here is the Tackback:

v = pims.Video('c:/Users/test2.mp4')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-e4b5659dfd2b> in <module>
----> 1 v = pims.Video('c:/Users/test2.mp4')

C:\ProgramData\Anaconda3\lib\site-packages\pims\pyav_reader.py in __init__(self, filename, cache_size, fast_forward_thresh, stream_index)
    137         # obtain first frame to get first time point
    138         # also tests for the presence of timestamps
--> 139         frame = next(_gen_frames(demuxer, self._stream.time_base))
    140         self._first_pts = frame.metadata['timestamp']
    141 

C:\ProgramData\Anaconda3\lib\site-packages\pims\pyav_reader.py in _gen_frames(demuxer, time_base, frame_rate, first_pts)
     52 
     53 def _gen_frames(demuxer, time_base, frame_rate=1., first_pts=0):
---> 54     for packet in demuxer:
     55         for frame in packet.decode():
     56             # learn timestamp

av\container\input.pyx in demux()

av\container\streams.pyx in _flatten()

TypeError: list indices must be integers or slices, not av.video.stream.VideoStream

**Comment by bjarthur** [comment] 2020-02-27 20:37
i can confirm av 6.2 is incompatible with pims.  downgrading to 0.4 fixes the above problem.

**Comment by tacaswell** [comment] 2020-02-28 20:03
Do we understand what changed in pyav

It looks like we are grabbing a stream object at https://github.com/soft-matter/pims/blob/c7a535842b5719fb950419431cca7cd56fb27598/pims/pyav_reader.py#L125

and then passing that into a demuxer object at https://github.com/soft-matter/pims/blob/c7a535842b5719fb950419431cca7cd56fb27598/pims/pyav_reader.py#L139

which eventually raises when we pull on it via https://github.com/soft-matter/pims/blob/c7a535842b5719fb950419431cca7cd56fb27598/pims/pyav_reader.py#L143

My guess is that we should pass `stream_index` directly into the demuxer at L139, but someone should check with pyav that this was an intentional change and not a bug on their part.

**Comment by danielballan** [comment] 2020-03-06 14:56
@mikeboers Do you have time to comment?

**Comment by mikeboers** [comment] 2020-03-08 23:53
The only thing I can imagine will result in that exception (in the current codebase) is if you do something like `demux(video=a_stream_object)`. I don't get it TBH.

**Comment by mikeboers** [comment] 2020-03-08 23:54
The tests pass a stream object into `demux` the same way... https://github.com/mikeboers/PyAV/blob/develop/tests/test_decode.py#L10-L21

**Comment by sofroniewn** [comment] 2020-03-12 20:02
Following a recommendation of @danielballan https://github.com/dask/dask-image/issues/134#issuecomment-593194727 I was also just trying pims + pyav and am running into the same issue. I just installed PyAV with 
```
conda install av -c conda-forge
```
to get `av==7.0.1`, and am using `pims==0.4.1` and am trying to read a standard `.mov` file. I have checked a couple files and always get this error message.
```python-traceback
    v = pims.Video(file)
  File "/Users/nsofroniew/opt/anaconda3/lib/python3.7/site-packages/pims/pyav_reader.py", line 139, in __init__
    frame = next(_gen_frames(demuxer, self._stream.time_base))
  File "/Users/nsofroniew/opt/anaconda3/lib/python3.7/site-packages/pims/pyav_reader.py", line 54, in _gen_frames
    for packet in demuxer:
  File "av/container/input.pyx", line 111, in demux
  File "av/container/streams.pyx", line 11, in _flatten
TypeError: list indices must be integers or slices, not av.video.stream.VideoStream
```
If i have time I can try and look into what is causing the problem

**Comment by sofroniewn** [comment] 2020-03-12 22:53
I've tried poking around a little, but havn't been able to make much progress. If I pass `stream_index` directly `self._container.demux(streams=stream_index)` to the demux I still get an error, this time
```
deprecated pixel format used, make sure you did set range correctly
```
If I dig into `PyAV` directly and just try the following

```python
import av
v = av.open('my_file.mov')
p = list(v.demux(streams=0))[0]
for f in p.decode():
    print(f)
```
I get the following error
```python-traceback
<ipython-input-57-181d755c44e8> in <module>
----> 1 for f in p.decode():
      2     print(f)
      3

av/packet.pyx in av.packet.Packet.decode()
av/stream.pyx in av.stream.Stream.decode()
av/codec/context.pyx in av.codec.context.CodecContext.decode()
av/codec/context.pyx in av.codec.context.CodecContext._send_packet_and_recv()
av/error.pyx in av.error.err_check()
EOFError: [Errno 541478725] End of file
```

**Comment by sofroniewn** [comment] 2020-03-13 18:19
So poking around some more I encountered some more potential problems - a `raise` instead of a `return` for example, but I then realized that these have been fixed on master. I'm currently using the latest release `0.4.1`, but it seems like it is quite old now (165 commits behind master). When I upgrade to master many of my problems go away (I also reinstalled my ffmpeg and did everything clean).

Now using `dask_image`

```python
from dask_image.imread import imread
movie = imread(file)
frame = np.asarray(movie[0])
```
However I still encounter the following warning - which it would be great if I didn't
```
WARNING:libav.swscaler:deprecated pixel format used, make sure you did set range correctly
/Users/nsofroniew/GitHub/pims/pims/pyav_reader.py:236: MethodDeprecationWarning: VideoStream.seek is deprecated.
  self._stream.seek(timestamp + self._first_pts)
```

First off curious if anyone has any ideas about how to improve the above, update to avoid the deprecation warning?

Also @danielballan can you give an update on when you're thinking about making the next release of PIMS?

**Comment by bjarthur** [comment] 2020-04-29 12:14
yup, `pip install https://github.com/soft-matter/pims/archive/master.zip` works for me too.  thanks @sofroniewn for figuring this out!

definitely would be nice to tag a new release as the current one is 2-1/2 yrs old.

i do however get this warning with master:

```
>>> import pims
Unable to init server: Could not connect: Connection refused

(.:23803): Gtk-WARNING **: 16:40:30.385: Locale not supported by C library.
	Using the fallback 'C' locale.
Unable to init server: Could not connect: Connection refused

(.:23803): Gdk-CRITICAL **: 16:40:30.386: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
```

this is inside a singularity container over an ssh connection.  is there a way to tell pims i don't want a GUI?

**Comment by nkeim** [comment] 2020-04-30 17:38
Agreed that a new release is overdue! I imagine that our maintainers (myself included) are figuring out how to fit it in now that our circumstances are changed.

The GUI is probably started because pims is importing matplotlib as it searches for available image-reading packages. That's where I would look. Also, it may be that by having a preferred image-reading package installed ('imageio'?) you can prevent pims from ever looking for matplotlib.

**Closed by nkeim** 2020-04-30 17:38 UTC
