### ISSUE TITLE
problems with export_pyav

### ISSUE THREAD

**Issue by mmdriscoll** [soft-matter/pims#279] opened 2017-10-13 17:07 UTC
I was hoping to use this function to export a pims object (cine file) as a .mp4.  When I try pims.display.export_pyav(im[0:10],'test.mp4'), I get a Segmentation fault: 11 and my python shell dies.  This should not be using a huge amount of memory, I am testing with just 10 frames of 512x384 pixel movie....

**Comment by nkeim** [comment] 2017-10-17 03:15
Hey! I don’t know much about PyAV, but: has it worked for other movies on the same computer? And, what are pims.__version__ and pyav.__version__?

On Oct 13, 2017, 10:07 AM -0700, Michelle Driscoll <notifications@github.com>, wrote:

I was hoping to use this function to export a pims object (cine file) as a .mp4. When I try pims.display.export_pyav(im[0:10],'test.mp4'), I get a Segmentation fault: 11 and my python shell dies. This should not be using a huge amount of memory, I am testing with just 10 frames of 512x384 pixel movie....

**Comment by mmdriscoll** [comment] 2017-10-17 17:05
It does not seem to work for other movies either - I get the same segmentation fault.  
pims version 0.4.1
pyav version 0.3.3

**Comment by nkeim** [comment] 2017-11-09 19:55
@mmdriscoll Have you tried a different codec? As in

`pims.display.export_pyav(im[0:10],'test.mov', codec='libx264')`

**Comment by mmdriscoll** [comment] 2017-11-09 21:43
@nkeim 

I have tried that; when I try the codec you suggest I get the following:

No handlers could be found for logger "libav.mov"

If I try this codec with mp4, i.e. pims.display.export_pyav(im[0:10],'test.avi', codec='libx264'),
ipython dies as follows:

pims.display.export_pyav(im[0:10],'test.mp4',codec='libx264')
Segmentation fault: 11

**Comment by caspervdw** [comment] 2018-06-29 20:22
Possible duplicate of #302

**Comment by nkeim** [comment] 2020-04-30 19:48
Closing. PyAV support was overhauled awhile ago; hopefully this is fixed.

**Closed by nkeim** 2020-04-30 19:48 UTC
