### ISSUE TITLE
TiffStack fails on IndexError from Tifffile

### ISSUE THREAD

**Issue by danielballan** [soft-matter/pims#134] opened 2015-01-27 14:45 UTC
Reported to me via email:

    >>> v=pims.TiffStack(f)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/christopher/.virtualenvs/wormvision3/lib/python3.4/site-packages/pims/tiff_stack.py", line 322, in __init__
        self.im.seek(j)
      File "/usr/lib/python3/dist-packages/PIL/TiffImagePlugin.py", line 626, in seek
        self._seek(frame)
      File "/usr/lib/python3/dist-packages/PIL/TiffImagePlugin.py", line 644, in _seek
        self.tag.load(self.fp)
      File "/usr/lib/python3/dist-packages/PIL/TiffImagePlugin.py", line 417, in load
        for i in range(i16(fp.read(2))):
      File "/usr/lib/python3/dist-packages/PIL/_binary.py", line 35, in i16be
        return (i8(c[o])<<8) | i8(c[o+1])
    IndexError: index out of range

I usually pass a file name, not file object, to `TiffStack` but file objects work fine too:

    In [2]: f = open('stuck.tif', 'r')

    In [3]: pims.TiffStack(f)
    Out[3]: 
    <Frames>
    Source: <open file 'stuck.tif', mode 'r' at 0x105d95810>
    Length: 5 frames
    Frame Shape: 512 x 512
    Pixel Datatype: <type 'numpy.uint16'>

It looks like this issue goes down all the way to tifffile. I'm not sure we can do anything except maybe fail more informatively.

**Comment by tacaswell** [comment] 2015-01-27 14:46
can you get us a copy of the file?

**Comment by 22csnyder** [comment] 2015-01-27 15:40
Hi I sent Daniel that error message,

Looking more closely: it doesn't seem to have to do with Python version as much as the file. I am though for the record in 64bit Python3.4. The file [attached] opens fine in ImageJ, but fails with v=pims.TiffStack('mypath'). pims.TiffStack('a_different_tiffstack') does manage to load with PIMS. Attached is the offending file.
...
Wait how can I send you the file if it's 400MB?
-Chris

**Comment by tacaswell** [comment] 2015-02-02 18:39
@22csnyder Can you put in on google drive or some publicly visible server?

**Comment by 22csnyder** [comment] 2015-02-02 20:59
Okay, I think I've done that correctly...Here you go:
https://drive.google.com/file/d/0B2DsQIFbCQmEZURuVnp6S195c2s/view?usp=sharing

It's much smaller ~12MB but it gives the same error message. Pardon the long filename.

Of note, I can't reproduce the error anymore on my PC.... I still generate the error on my Ubuntu.
-Chris

**Comment by tacaswell** [comment] 2015-02-02 21:38
I would also try installing tiffile and/or pillow, not sure I would trust PIL to deal with scientific tiffs (which tend to have odd bit depths).

**Comment by 22csnyder** [comment] 2015-02-02 21:42
It's 16bit unsigned. Is that weird? I haven't had trouble before with 16bitU. Also, documentation says tiffle is included in PIMS : https://github.com/soft-matter/pims.

I could try pillow

**Comment by tacaswell** [comment] 2015-02-02 21:55
oh, that documentation is wrong, we unbundled a while ago...

**Comment by danielballan** [comment] 2015-02-03 12:05
@22csnyder if you install pims using conda, like `conda install -c soft-matter pims`, then you get tifffile. Otherwise you have to install it yourself, either `conda install -c soft-matter tiffffile` or  `pip install tifffile`.

**Comment by 22csnyder** [comment] 2015-02-05 16:33
But probably tifffile is not my problem. I can see the tifffile.py, tifffile-0.4-py3.4.egg-info, and 
_tifffile.cpython-34m.so file in site packages. And, in python I do
import tifffile
tifffile.__file__
I get a path leading to that same tifffile.py

**Comment by cgohlke** [comment] 2015-02-25 10:12
The file `141226_ZIM294 HiRes_L4_O20X_F630x75um_P11008x500S173 stack.tif` is corrupt. The ImageJ comment claims there are 101 images/slices in the file. There appear to be only two. Libtiff also fails to read the directories.

**Comment by danielballan** [comment] 2015-02-25 16:38
Thanks, @cgohlke.

**Comment by tacaswell** [comment] 2015-06-19 17:51
Closing as this was an issue with bad input files.

**Closed by tacaswell** 2015-06-19 17:51 UTC
